### ISSUE TITLE
Create proper testing infrastructure

### ISSUE THREAD

**Issue by claudio-viola** [FredericHeem/starhackit#18]
Testing needs to be improved and properly structured in a separate test folder.

At the moment the examples present on the server side are doing integration testing.
Need to provide proper unit testing ---> 
Suggested to use Proxyquire for dependency injection and mocking with sinon.
https://github.com/thlorenz/proxyquire

**Comment by FredericHeem** [comment]
tests was on a separate test folder but I believe tests should be as close as the code to test, that's why they are now beside the code being tested.
By the way the *sinon* mocking library  is already used.
unit testing is useful but integration testing rules.
Code coverage is above 90% so there is already a proper testing infrastructure on the backend side.

**Comment by claudio-viola** [comment]
Integration testing and unit testing should be kept separated. 
If you are aim is to provide a starter kit, things should be done in the proper and right way.
No need to discuss further as you are aware of it but I suggest you rethink about it.
